### ISSUE TITLE
Reading chat?

### ISSUE THREAD

**Issue by fmckeogh** [hatmatter/twitch_api#1]
Hello,

Is there any way to use your API for reading chat messages? Eg, join a given stream and save messages as an array of strings?

Thanks!

**Comment by theGeekPirate** [comment]
Twitch chat is done using a minimal version of the IRC spec, and has nothing to do with their API, so that probably isn't within the scope of this project, unfortunately.

The good news being, of course, that any IRC library should work =)

**Comment by fmckeogh** [comment]
Thanks! :)
